// ErrorMsgCtrl.h: interface for the CErrorMsgCtrl class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_AOIEXCEPTIONCODEDEF_H__2447BA75_1722_439F_A460_1CE9EC540916__INCLUDED_)
#define AFX_AOIEXCEPTIONCODEDEF_H__2447BA75_1722_439F_A460_1CE9EC540916__INCLUDED_
//-------------------------------------------------------------------------------------//
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
//-------------------------------------------------------------------------------------//
enum AOI_EXCEPTION_CODE//AOI異常碼
{
	AOI_EXCEPTION_NONE                      =    0,//沒有異常-成功
	AOI_EXCEPTION_OTHERS                    =    1,//其他異常-未定義

	AOI_EXCEPTION_MEMORY_BEGIN              =  100,//記憶體-錯誤訊息開始
	AOI_EXCEPTION_MEMORY_ALLOC              =  101,//記憶體-建立失敗
	AOI_EXCEPTION_MEMORY_FREE               =  102,//記憶體-釋放失敗
	AOI_EXCEPTION_MEMORY_OTHERS             =  199,//記憶體-錯誤訊息

	AOI_EXCEPTION_OBJECT_BEGIN              =  200,//AOI物件-錯誤訊息開始
	AOI_EXCEPTION_OBJECT_CREATE             =  201,//AOI物件-建立失敗
	AOI_EXCEPTION_OBJECT_DELETE             =  202,//AOI物件-釋放失敗
	AOI_EXCEPTION_OBJECT_OTHERS             =  299,//AOI物件-錯誤訊息

	AOI_EXCEPTION_CAMERA_BEGIN              =  300,//相機-錯誤訊息開始		
	AOI_EXCEPTION_CAMERA_PARAM              =  301,//相機-參數異常	
	AOI_EXCEPTION_CAMERA_SET_FUNC           =  302,//相機-設定函式
	AOI_EXCEPTION_CAMERA_GET_FUNC           =  303,//相機-取回函式
	AOI_EXCEPTION_CAMERA_EXEC_FUNC          =  304,//相機-執行函式	
	//AOI_EXCEPTION_CAMERA_FILE_READ          =  308,//相機-檔案讀取
	//AOI_EXCEPTION_CAMERA_FILE_WRITE         =  309,//相機-檔案寫入
	AOI_EXCEPTION_CAMERA_CONNECT            =  311,//相機-連線階段
	AOI_EXCEPTION_CAMERA_RELEASE            =  312,//相機-釋放階段
	AOI_EXCEPTION_CAMERA_RESET              =  313,//相機-重置
	AOI_EXCEPTION_CAMERA_GRAB_STOP          =  314,//相機-取像停止
	AOI_EXCEPTION_CAMERA_GRAB_START         =  315,//相機-取像開始	
	AOI_EXCEPTION_CAMERA_GRAB_MODE          =  316,//相機-取像模式	
	AOI_EXCEPTION_CAMERA_EXP_TIME_FUNC      =  317,//相機-曝光時間函式
	AOI_EXCEPTION_CAMERA_SOFT_TRIG_FUNC     =  318,//相機-軟體觸發函式
	AOI_EXCEPTION_CAMERA_READY_TRIG_FUNC    =  319,//相機-等待可觸發函式
	AOI_EXCEPTION_CAMERA_WHITE_BALANCE_FUNC =  320,//相機-白平衡相關函式	
	AOI_EXCEPTION_CAMERA_RING_BUFFER        =  387,//相機-循環記憶體指標
	AOI_EXCEPTION_CAMERA_EXP_DONE_FUNC      =  388,//相機-曝光結束函式
	AOI_EXCEPTION_CAMERA_GRAB_DONE_FUNC     =  389,//相機-取像結束函式
	AOI_EXCEPTION_CAMERA_EXEC_CALI_FUNC     =  398,//相機-執行校正函式
	AOI_EXCEPTION_CAMERA_OTHERS             =  399,//相機-錯誤訊息

	AOI_EXCEPTION_MOTION_BEGIN              =  400,//軸控-錯誤訊息開始	
	AOI_EXCEPTION_MOTION_PARAM              =  401,//軸控-參數異常	
	AOI_EXCEPTION_MOTION_SET_FUNC           =  402,//軸控-設定函式
	AOI_EXCEPTION_MOTION_GET_FUNC           =  403,//軸控-取回函式
	AOI_EXCEPTION_MOTION_EXEC_FUNC          =  404,//軸控-執行函式		
	//AOI_EXCEPTION_MOTION_FILE_READ          =  408,//軸控-檔案讀取
	//AOI_EXCEPTION_MOTION_FILE_WRITE         =  409,//軸控-檔案寫入
	AOI_EXCEPTION_MOTION_CONNECT            =  411,//軸控-連線階段
	AOI_EXCEPTION_MOTION_RELEASE            =  412,//軸控-釋放階段	
	AOI_EXCEPTION_MOTION_HOME               =  413,//軸控-歸零階段	
	AOI_EXCEPTION_MOTION_MOVE               =  414,//軸控-移動階段
	AOI_EXCEPTION_MOTION_MOVE_DONE          =  415,//軸控-移動結束
	AOI_EXCEPTION_MOTION_FAULT_ACK          =  416,//軸控-錯誤響應
	AOI_EXCEPTION_MOTION_ENABLE             =  417,//軸控-啟用
	AOI_EXCEPTION_MOTION_DISABLE            =  418,//軸控-停用
	AOI_EXCEPTION_MOTION_INP_FUNC           =  419,//軸控-INP函式	
	AOI_EXCEPTION_MOTION_READ_ENCODE        =  420,//軸控-讀取編碼值
	AOI_EXCEPTION_MOTION_JOG_FUNC           =  421,//軸控-遙動函式		
	AOI_EXCEPTION_MOTION_GANTRY_FUNC        =  422,//軸控-龍門函式
	AOI_EXCEPTION_MOTION_LIMIT_CALI         =  423,//軸控-機台極限校正
	AOI_EXCEPTION_MOTION_LIMIT_RANGE        =  424,//軸控-機台極限範圍
	AOI_EXCEPTION_MOTION_NOT_READY          =  425,//軸控-尚未準備好
	AOI_EXCEPTION_MOTION_PARAM_XY_CALI      =  426,//軸控-參數異常-XY精度校正
	AOI_EXCEPTION_MOTION_OTHERS             =  499,//軸控-錯誤訊息

	AOI_EXCEPTION_PLC_BEGIN                 =  500,//PLC-錯誤訊息開始	
	AOI_EXCEPTION_PLC_PARAM                 =  501,//PLC-參數異常	
	AOI_EXCEPTION_PLC_SET_FUNC              =  502,//PLC-設定函式
	AOI_EXCEPTION_PLC_GET_FUNC              =  503,//PLC-取回函式
	AOI_EXCEPTION_PLC_EXEC_FUNC             =  504,//PLC-執行函式
	AOI_EXCEPTION_PLC_WRITE_NODE            =  505,//PLC-寫入PLC
	AOI_EXCEPTION_PLC_READ_NODE             =  506,//PLC-讀取PLC	
	//AOI_EXCEPTION_PLC_FILE_READ             =  508,//PLC-檔案讀取
	//AOI_EXCEPTION_PLC_FILE_WRITE            =  509,//PLC-檔案寫入
	AOI_EXCEPTION_PLC_CONNECT               =  511,//PLC-連線
	AOI_EXCEPTION_PLC_EMERGENCY             =  512,//PLC-緊急停止
	AOI_EXCEPTION_PLC_KEY_SWITCH            =  513,//PLC-鑰匙開關
	AOI_EXCEPTION_PLC_SAFTY_ALARM           =  514,//PLC-安全警報
	AOI_EXCEPTION_PLC_OVER_HEAT             =  515,//PLC-過熱警報
	AOI_EXCEPTION_PLC_FAN_ALARM             =  516,//PLC-風扇異常
	AOI_EXCEPTION_PLC_DOOR_OPEN             =  517,//PLC-前後門開啟
	AOI_EXCEPTION_PLC_AIR_LOST              =  518,//PLC-氣壓不足
	AOI_EXCEPTION_PLC_PCB_IN_LA             =  530,//PLC-進板錯誤-A軌道	
	AOI_EXCEPTION_PLC_PCB_OUT_LA            =  531,//PLC-出板錯誤-A軌道
	AOI_EXCEPTION_PLC_PCB_BACK_LA           =  532,//PLC-退板錯誤-A軌道
	AOI_EXCEPTION_PLC_PCB_OUT_IN_LA         =  533,//PLC-出板帶進板錯誤-A軌道
	AOI_EXCEPTION_PLC_PCB_IN_OUT_LA         =  534,//PLC-進出板錯誤-A軌道
	AOI_EXCEPTION_PLC_PCB_IN_BACK_LA        =  535,//PLC-進退板錯誤-A軌道
	AOI_EXCEPTION_PLC_PCB_CLEAR_LA          =  536,//PLC-清板錯誤-A軌道
	AOI_EXCEPTION_PLC_PCB_BARGE_IN_LA       =  537,//PLC-闖板錯誤-A軌道
	AOI_EXCEPTION_PLC_PCB_BACK_OUT_LA       =  538,//PLC-退出板錯誤-A軌道
	AOI_EXCEPTION_PLC_LANE_ADJUST_HOME_LA   =  548,//PLC-軌道寬度歸零-A軌道
	AOI_EXCEPTION_PLC_LANE_ADJUST_MOVE_LA   =  549,//PLC-軌道寬度移動-A軌道
	AOI_EXCEPTION_PLC_PCB_IN_LB             =  550,//PLC-進板錯誤-B軌道
	AOI_EXCEPTION_PLC_PCB_OUT_LB            =  551,//PLC-出板錯誤-B軌道	
	AOI_EXCEPTION_PLC_PCB_BACK_LB           =  552,//PLC-退板錯誤-B軌道
	AOI_EXCEPTION_PLC_PCB_OUT_IN_LB         =  553,//PLC-出板帶進板錯誤-B軌道
	AOI_EXCEPTION_PLC_PCB_IN_OUT_LB         =  554,//PLC-進出板錯誤-B軌道
	AOI_EXCEPTION_PLC_PCB_IN_BACK_LB        =  555,//PLC-進退板錯誤-B軌道
	AOI_EXCEPTION_PLC_PCB_CLEAR_LB          =  556,//PLC-清板錯誤-B軌道	
	AOI_EXCEPTION_PLC_PCB_BARGE_IN_LB       =  557,//PLC-闖板錯誤-B軌道
	AOI_EXCEPTION_PLC_PCB_BACK_OUT_LB       =  558,//PLC-退出板錯誤-B軌道	
	AOI_EXCEPTION_PLC_LANE_ADJUST_HOME_LB   =  568,//PLC-軌道寬度歸零-B軌道
	AOI_EXCEPTION_PLC_LANE_ADJUST_MOVE_LB   =  569,//PLC-軌道寬度移動-B軌道
	AOI_EXCEPTION_PLC_OTHERS                =  599,//PLC-錯誤訊息

	AOI_EXCEPTION_LIGHT_CTRL_BEGIN          =  600,//燈控-錯誤訊息開始		
	AOI_EXCEPTION_LIGHT_CTRL_PARAM          =  601,//燈控-參數異常	
	AOI_EXCEPTION_LIGHT_CTRL_SET_FUNC       =  602,//燈控-設定函式
	AOI_EXCEPTION_LIGHT_CTRL_GET_FUNC       =  603,//燈控-取回函式
	AOI_EXCEPTION_LIGHT_CTRL_EXEC_FUNC      =  604,//燈控-執行函式
	AOI_EXCEPTION_LIGHT_CTRL_READ           =  605,//燈控-讀取階段
	AOI_EXCEPTION_LIGHT_CTRL_WRITE          =  606,//燈控-寫入階段	
	//AOI_EXCEPTION_LIGHT_CTRL_FILE_READ      =  608,//燈控-檔案存取
	//AOI_EXCEPTION_LIGHT_CTRL_FILE_WRITE     =  609,//燈控-檔案寫入
	AOI_EXCEPTION_LIGHT_CTRL_CONNECT        =  611,//燈控-連線階段
	AOI_EXCEPTION_LIGHT_CTRL_RELEASE        =  612,//燈控-釋放階段	
	AOI_EXCEPTION_LIGHT_CTRL_CLEAR          =  613,//燈控-清除資料
	AOI_EXCEPTION_LIGHT_CTRL_TRIGGER        =  614,//燈控-觸發開始
	AOI_EXCEPTION_LIGHT_CTRL_LOOP_BACK      =  615,//燈控-迴圈測試	
	AOI_EXCEPTION_LIGHT_CTRL_TABLE_READ     =  621,//燈控-表格讀取
	AOI_EXCEPTION_LIGHT_CTRL_TABLE_WRITE    =  622,//燈控-表格寫入
	AOI_EXCEPTION_LIGHT_CTRL_TABLE_CONVERT  =  623,//燈控-表格轉換
	AOI_EXCEPTION_LIGHT_CTRL_TABLE_COMPARE  =  624,//燈控-表格比較
	AOI_EXCEPTION_LIGHT_CTRL_CONVEYOR_FUNC  =  698,//燈控-軌道操作
	AOI_EXCEPTION_LIGHT_CTRL_OTHERS         =  699,//燈控-錯誤訊息

	AOI_EXCEPTION_DLP_CTRL_BEGIN            =  700,//DLP-錯誤訊息開始	
	AOI_EXCEPTION_DLP_CTRL_PARAM            =  701,//DLP-參數異常
	AOI_EXCEPTION_DLP_CTRL_SET_FUNC         =  702,//DLP-設定函式
	AOI_EXCEPTION_DLP_CTRL_GET_FUNC         =  703,//DLP-取回函式
	AOI_EXCEPTION_DLP_CTRL_EXEC_FUNC        =  704,//DLP-執行函式
	AOI_EXCEPTION_DLP_CTRL_READ             =  705,//DLP-讀取階段
	AOI_EXCEPTION_DLP_CTRL_WRITE            =  706,//DLP-寫入階段	
	//AOI_EXCEPTION_DLP_CTRL_FILE_READ        =  708,//DLP-檔案讀取
	//AOI_EXCEPTION_DLP_CTRL_FILE_WRITE       =  709,//DLP-檔案寫入
	AOI_EXCEPTION_DLP_CTRL_CONNECT          =  711,//DLP-裝置連線
	AOI_EXCEPTION_DLP_CTRL_DISCONNECT       =  712,//DLP-裝置釋放
	AOI_EXCEPTION_DLP_CTRL_RESET            =  713,//DLP-裝置重啟
	AOI_EXCEPTION_DLP_CTRL_LIGHT_SETTING    =  721,//DLP-燈源設定
	AOI_EXCEPTION_DLP_CTRL_PATTERN_PLAY     =  722,//DLP-樣板播放
	AOI_EXCEPTION_DLP_CTRL_PATTERN_STOP     =  723,//DLP-樣板停止
	AOI_EXCEPTION_DLP_CTRL_PATTERN_PAUSE    =  724,//DLP-樣板暫停
	AOI_EXCEPTION_DLP_CTRL_PATTERN_READ     =  725,//DLP-樣板讀取
	AOI_EXCEPTION_DLP_CTRL_PATTERN_SEND_ONE =  726,//DLP-樣板傳送1個
	AOI_EXCEPTION_DLP_CTRL_PATTERN_SEND_ALL =  727,//DLP-樣板傳送全部	
	AOI_EXCEPTION_DLP_CTRL_PATTERN_VALIDATE =  728,//DLP-樣板驗證
	AOI_EXCEPTION_DLP_CTRL_OTHERS           =  799,//DLP-錯誤訊息

	AOI_EXCEPTION_BARCODE_DEVICE_BEGIN      =  800,//條碼機-錯誤訊息開始	
	AOI_EXCEPTION_BARCODE_DEVICE_PARAM      =  801,//條碼機-參數異常
	AOI_EXCEPTION_BARCODE_DEVICE_SET_FUNC   =  802,//條碼機-設定函式
	AOI_EXCEPTION_BARCODE_DEVICE_GET_FUNC   =  803,//條碼機-取回函式
	AOI_EXCEPTION_BARCODE_DEVICE_EXEC_FUNC  =  804,//條碼機-執行函式
	//AOI_EXCEPTION_BARCODE_DEVICE_FILE_READ  =  808,//條碼機-檔案讀取
	//AOI_EXCEPTION_BARCODE_DEVICE_FILE_WRITE =  809,//條碼機-檔案寫入
	AOI_EXCEPTION_BARCODE_DEVICE_CREATE     =  811,//條碼機-建立階段
	AOI_EXCEPTION_BARCODE_DEVICE_CONNECT    =  812,//條碼機-連線階段	
	AOI_EXCEPTION_BARCODE_DEVICE_START      =  813,//條碼機-開始階段
	AOI_EXCEPTION_BARCODE_DEVICE_DECODE     =  814,//條碼機-解碼階段
	AOI_EXCEPTION_BARCODE_DEVICE_OTHERS     =  899,//條碼機-錯誤訊息
	
	AOI_EXCEPTION_MES_BEGIN                 =  900,//MES-錯誤訊息開始	
	AOI_EXCEPTION_MES_PARAM                 =  901,//MES-參數異常
	AOI_EXCEPTION_MES_SET_FUNC              =  902,//MES-設定函式
	AOI_EXCEPTION_MES_GET_FUNC              =  903,//MES-取回函式
	AOI_EXCEPTION_MES_ASK_FUNC              =  904,//MES-詢問函式
	AOI_EXCEPTION_MES_EXEC_FUNC             =  905,//MES-執行函式	
	AOI_EXCEPTION_MES_UPLOAD_FUNC           =  906,//MES-上傳函式
	AOI_EXCEPTION_MES_DOWNLOAD_FUNC         =  907,//MES-下載函式
	//AOI_EXCEPTION_MES_FILE_READ             =  908,//MES-檔案讀取
	//AOI_EXCEPTION_MES_FILE_WITE             =  909,//MES-檔案寫入
	AOI_EXCEPTION_MES_CREATE                =  911,//MES-創建階段
	AOI_EXCEPTION_MES_CONNECT               =  912,//MES-連線階段
	AOI_EXCEPTION_MES_DISCONNECT            =  913,//MES-斷線階段
	AOI_EXCEPTION_MES_SEND                  =  914,//MES-傳送階段
	AOI_EXCEPTION_MES_RECV                  =  915,//MES-接收階段		
	AOI_EXCEPTION_MES_GET_MES_READY         =  920,//MES-取得MES就緒
	AOI_EXCEPTION_MES_SET_SYSTEM_PARAM      =  921,//MES-設定系統參數
	AOI_EXCEPTION_MES_SET_PROJECT_PARAM     =  922,//MES-設定專案參數
	AOI_EXCEPTION_MES_SET_MACHINE_STATUS    =  923,//MES-設定機台狀態
	AOI_EXCEPTION_MES_SET_PROCESS_ID        =  924,//MES-設定程序編號
	AOI_EXCEPTION_MES_SET_CONTROL_STATE     =  925,//MES-設定控制狀態
	AOI_EXCEPTION_MES_BARCODE_CHECK         =  926,//MES-條碼確認
	AOI_EXCEPTION_MES_BARCODE_ASK           =  927,//MES-條碼詢問	
	AOI_EXCEPTION_MES_BOARD_MAPPING         =  928,//MES-報廢板映射
	AOI_EXCEPTION_MES_LOGOUT_LOGIN          =  929,//MES-使用者登出入
	AOI_EXCEPTION_MES_UNCHECK_TEST_FILE     =  930,//MES-未判定檢測檔案數
	AOI_EXCEPTION_MES_OTHERS                =  999,//MES-錯誤訊息

	AOI_EXCEPTION_CUDA_BEGIN                = 1000,//Cuda-錯誤訊息開始		
	AOI_EXCEPTION_CUDA_PARAM                = 1001,//Cuda-參數異常
	AOI_EXCEPTION_CUDA_SET_FUNC             = 1002,//Cuda-設定函式
	AOI_EXCEPTION_CUDA_GET_FUNC             = 1003,//Cuda-取回函式
	AOI_EXCEPTION_CUDA_EXEC_FUNC            = 1004,//Cuda-執行函式
	//AOI_EXCEPTION_CUDA_FILE_READ            = 1008,//Cuda-檔案讀取
	//AOI_EXCEPTION_CUDA_FILE_WRITE           = 1009,//Cuda-檔案寫入
	AOI_EXCEPTION_CUDA_INIT                 = 1011,//Cuda-初始化Cuda	
	AOI_EXCEPTION_CUDA_MEM_ALLOC            = 1021,//Cuda-建立記憶體
	AOI_EXCEPTION_CUDA_MEM_FREE             = 1022,//Cuda-釋放記憶體
	AOI_EXCEPTION_CUDA_MEM_COPY             = 1023,//Cuda-複製記憶體
	AOI_EXCEPTION_CUDA_DISABLED             = 1098,//Cuda-關閉Cuda
	AOI_EXCEPTION_CUDA_OTHERS               = 1099,//Cuda-錯誤訊息

	AOI_EXCEPTION_FILE_BEGIN                = 1100,//檔案-錯誤訊息
	AOI_EXCEPTION_FILE_READ                 = 1101,//檔案-讀取
	AOI_EXCEPTION_FILE_WRITE                = 1102,//檔案-寫入
	AOI_EXCEPTION_FILE_OTHERS               = 1199,//檔案-錯誤訊息

	AOI_EXCEPTION_THREAD_BEGIN                    = 1200,//執行緒-錯誤訊息
	AOI_EXCEPTION_THREAD_CREATE                   = 1201,//執行緒-建立
	AOI_EXCEPTION_THREAD_DELETE                   = 1202,//執行緒-刪除
	AOI_EXCEPTION_THREAD_START                    = 1203,//執行緒-啟動
	AOI_EXCEPTION_THREAD_IDLE                     = 1204,//執行緒-閒置
	AOI_EXCEPTION_THREAD_EXECUTION                = 1205,//執行緒-執行
	AOI_EXCEPTION_THREAD_WAIT_FOR_IDLE            = 1206,//執行緒-等待閒置	
	AOI_EXCEPTION_THREAD_WAIT_FOR_STOP            = 1207,//執行緒-等待停止
	AOI_EXCEPTION_THREAD_WAIT_FOR_START           = 1208,//執行緒-等待啟動
	AOI_EXCEPTION_THREAD_WAIT_FOR_FINISH          = 1209,//執行緒-等待完成
	AOI_EXCEPTION_THREAD_EXEC_SLICE_FILL          = 1210,//執行緒-執行-填滿相機圖像	
	AOI_EXCEPTION_THREAD_EXEC_FRAME_MERGE         = 1211,//執行緒-執行-合併單張圖像	
	AOI_EXCEPTION_THREAD_EXEC_FIELD_MERGE         = 1212,//執行緒-執行-合併視野圖像	
	AOI_EXCEPTION_THREAD_EXEC_REGION_CALC         = 1213,//執行緒-執行-計算區域資料	
	AOI_EXCEPTION_THREAD_EXEC_FIELD_CALC          = 1214,//執行緒-執行-計算視野圖像	
	AOI_EXCEPTION_THREAD_EXEC_FRAME_LOAD          = 1215,//執行緒-執行-載入單張圖像	
	AOI_EXCEPTION_THREAD_EXEC_FRAME_FIELD_FREE    = 1216,//執行緒-執行-釋放視野圖像	
	AOI_EXCEPTION_THREAD_EXEC_SEQUENCE            = 1217,//執行緒-執行-程序流程	
	AOI_EXCEPTION_THREAD_EXEC_ONLINE_INSPECTION   = 1218,//執行緒-執行-線上檢測	
	AOI_EXCEPTION_THREAD_EXEC_REMOVE_FOLDER       = 1219,//執行緒-執行-移除資料夾	
	AOI_EXCEPTION_THREAD_EXEC_CONVEYER_AUTO_RUN   = 1220,//執行緒-執行-軌道自動運轉		
	AOI_EXCEPTION_THREAD_EXEC_LOAD_REPAIR_FILE    = 1221,//執行緒-執行-載入維修站檔案
	AOI_EXCEPTION_THREAD_EXEC_REPAIR_RESULT_SIGNAL= 1222,//執行緒-執行-維修站結果訊號	
	AOI_EXCEPTION_THREAD_EXEC_SIMPLE_JOB          = 1223,//執行緒-執行-簡單作業	
	AOI_EXCEPTION_THREAD_EXEC_RELOAD_PROJECT      = 1224,//執行緒-執行-載入專案
	AOI_EXCEPTION_THREAD_EXEC_PROJECT_SAVE_FIELD  = 1241,//執行緒-執行-專案儲存視野
	AOI_EXCEPTION_THREAD_EXEC_PROJECT_COPY_FILE   = 1242,//執行緒-執行-專案複製檔案	
	AOI_EXCEPTION_THREAD_EXEC_HASI_MONITER        = 1261,//執行緒-執行-HASI 監控資料夾
	AOI_EXCEPTION_THREAD_OTHERS                   = 1299,//執行緒-錯誤訊息

	AOI_EXCEPTION_PROJECT_START             = 2000,//專案-錯誤訊息開始
	AOI_EXCEPTION_PROJECT_PARAM             = 2001,//專案-參數異常
	AOI_EXCEPTION_PROJECT_SET_FUNC          = 2002,//專案-設定函式
	AOI_EXCEPTION_PROJECT_GET_FUNC          = 2003,//專案-取回函式
	AOI_EXCEPTION_PROJECT_EXEC_FUNC         = 2004,//專案-執行函式
	//AOI_EXCEPTION_PROJECT_FILE_READ         = 2008,//專案-檔案讀取
	//AOI_EXCEPTION_PROJECT_FILE_WRITE        = 2009,//專案-檔案寫入	
	//AOI_EXCEPTION_PROJECT_MAP_START         = 2100,//專案-底圖-開始
	AOI_EXCEPTION_PROJECT_MAP_CREATE        = 2101,//專案-底圖-建立
	AOI_EXCEPTION_PROJECT_MAP_VALID         = 2102,//專案-底圖-有效	
	//AOI_EXCEPTION_PROJECT_MAP_MASK_START    = 2120,//專案-底圖遮罩-開始
	AOI_EXCEPTION_PROJECT_MAP_MASK_CREATE   = 2121,//專案-底圖遮罩-建立
	AOI_EXCEPTION_PROJECT_MAP_MASK_VALID    = 2122,//專案-底圖遮罩-有效(NULL)
	//AOI_EXCEPTION_PROJECT_MARK_IMAGE_START  = 2140,//專案-特徵圖-開始	
	AOI_EXCEPTION_PROJECT_MARK_IMAGE_TEST   = 2141,//專案-特徵圖-檢測	
	//AOI_EXCEPTION_PROJECT_TEST_MAP_START    = 2160,//專案-檢測底圖-開始
	AOI_EXCEPTION_PROJECT_TEST_MAP_CREATE   = 2161,//專案-檢測底圖-建立
	AOI_EXCEPTION_PROJECT_TEST_MAP_VALID    = 2162,//專案-檢測底圖-有效	
	//AOI_EXCEPTION_PROJECT_FIELD_START       = 2180,//專案-視野-開始
	AOI_EXCEPTION_PROJECT_FIELD_CREATE      = 2181,//專案-視野-建立
	AOI_EXCEPTION_PROJECT_FIELD_ADJUST      = 2182,//專案-視野-調整
	AOI_EXCEPTION_PROJECT_FIELD_FILL        = 2183,//專案-視野-填滿-Offline
	AOI_EXCEPTION_PROJECT_FIELD_PRE_LOAD    = 2184,//專案-視野-預載-Offline
	//AOI_EXCEPTION_PROJECT_PANEL_START       = 2200,//專案-整板-開始	
	//AOI_EXCEPTION_PROJECT_BOARD_START       = 2250,//專案-整板-開始
	//AOI_EXCEPTION_PROJECT_FD_START          = 2300,//專案-定位點-開始
	AOI_EXCEPTION_PROJECT_FD_MATCH          = 2301,//專案-定位點-搜尋
	//AOI_EXCEPTION_PROJECT_MARK_START        = 2350,//專案-特徵點-開始
	//AOI_EXCEPTION_PROJECT_BARCODE_START     = 2400,//專案-條碼-開始
	AOI_EXCEPTION_PROJECT_BARCODE_DECODE    = 2401,//專案-條碼-解碼	
	AOI_EXCEPTION_PROJECT_BARCODE_INPUT     = 2402,//專案-條碼-輸入
	//AOI_EXCEPTION_PROJECT_COMPONENT_START   = 2450,//專案-零件-開始
	AOI_EXCEPTION_PROJECT_COMPONENT_AGENT   = 2471,//專案-零件-代理	
	//AOI_EXCEPTION_PROJECT_MODEL_START       = 2500,//專案-模組-開始	

	AOI_EXCEPTION_PROJECT_TEST_DIMENSION    = 2997,//專案-檢測-尺寸
	AOI_EXCEPTION_PROJECT_TEST_SCRATCH      = 2998,//專案-檢測-刮傷
	AOI_EXCEPTION_PROJECT_TEST_DROPOUT      = 2999,//專案-檢測-拋件

	AOI_EXCEPTION_PROJECT_CALC_STAGE_POS    = 3001,//專案-計算-機台座標
	AOI_EXCEPTION_PROJECT_CALC_CAD_RESULT   = 3002,//專案-計算-CAD結果座標
	AOI_EXCEPTION_PROJECT_IMAGE_CONFIG_VALID= 3003,//專案-影像設定-有效		
	AOI_EXCEPTION_PROJECT_CREATE_GRAB_MAP_OBJ= 3004,//專案-建立-擷取底圖物件
	AOI_EXCEPTION_PROJECT_CREATE_PANEL_ALIGN_OBJ= 3005,//專案-建立-整板對齊物件
	AOI_EXCEPTION_PROJECT_CREATE_BOARD_ALIGN_OBJ= 3006,//專案-建立-單板對齊物件
	AOI_EXCEPTION_PROJECT_CREATE_INSPECTION_OBJ=3007,//專案-建立-檢測產品物件
	AOI_EXCEPTION_PROJECT_OTHERS            = 3999,//專案-錯誤訊息

	AOI_EXCEPTION_SYSTEM_START              =10000,//系統-錯誤訊息開始	
	AOI_EXCEPTION_SYSTEM_PARAM              =10001,//系統-參數異常
	//AOI_EXCEPTION_SYSTEM_SET_FUNC           =10002,//系統-設定函式
	//AOI_EXCEPTION_SYSTEM_GET_FUNC           =10003,//系統-取回函式
	//AOI_EXCEPTION_SYSTEM_EXEC_FUNC          =10004,//系統-執行函式
	//AOI_EXCEPTION_SYSTEM_FILE_READ          =10011,//系統-檔案-讀取
	//AOI_EXCEPTION_SYSTEM_FILE_WRITE         =10012,//系統-檔案-寫入
	//AOI_EXCEPTION_SYSTEM_MEMORY_ALLOC       =10021,//系統-記憶體-建立失敗
	//AOI_EXCEPTION_SYSTEM_MEMORY_FREE        =10022,//系統-記憶體-釋放失敗	
	//AOI_EXCEPTION_SYSTEM_OBJECT_CREATE      =10031,//系統-AOI物件-建立失敗
	//AOI_EXCEPTION_SYSTEM_OBJECT_DELETE      =10032,//系統-AOI物件-釋放失敗

	AOI_EXCEPTION_SYSTEM_EXEC_PROJECT_MAP      =10101,//系統-執行-專案底圖
	AOI_EXCEPTION_SYSTEM_EXEC_PROJECT_ALIGN    =10102,//系統-執行-專案對齊
	AOI_EXCEPTION_SYSTEM_EXEC_OFFLINE_ALIGN    =10103,//系統-執行-離線對齊
	AOI_EXCEPTION_SYSTEM_EXEC_OFFLINE_EXPORT   =10104,//系統-執行-離線輸出
	AOI_EXCEPTION_SYSTEM_EXEC_PROJECT_TUNING   =10105,//系統-執行-專案調適
	AOI_EXCEPTION_SYSTEM_EXEC_OFFLINE_TUNING   =10106,//系統-執行-離線調適
	AOI_EXCEPTION_SYSTEM_EXEC_PROJECT_INSPECT  =10107,//系統-執行-專案檢測

	AOI_EXCEPTION_SYSTEM_GRAB_IMAGE_CNT     =10201,//系統-取像-影像數量
	AOI_EXCEPTION_SYSTEM_CHEK_PROJECT       =10202,//系統-確認-專案指標

	AOI_EXCEPTION_SYSTEM_OTHERS             =19999,//系統-錯誤訊息

	AOI_EXCEPTION_CALCULATION_START         =20000,//資料計算-錯誤訊息開始	
	AOI_EXCEPTION_CALCULATION_PARAM         =20001,//資料計算-參數異常
	AOI_EXCEPTION_CALCULATION_SET_FUNC      =20002,//資料計算-設定函式
	AOI_EXCEPTION_CALCULATION_GET_FUNC      =20003,//資料計算-取回函式
	AOI_EXCEPTION_CALCULATION_EXEC_FUNC     =20004,//資料計算-執行函式
	//AOI_EXCEPTION_CALCULATION_MEM_ALLOC     =20006,//資料計算-記憶體配置
	//AOI_EXCEPTION_CALCULATION_MEM_FREE      =20007,//資料計算-記憶體釋放
	//AOI_EXCEPTION_CALCULATION_FILE_READ     =20008,//資料計算-檔案讀取
	//AOI_EXCEPTION_CALCULATION_FILE_WRITE    =20009,//資料計算-檔案寫入
	AOI_EXCEPTION_CALCULATION_OPENCV_API    =20021,//資料計算-執行OpenCV函式庫
	AOI_EXCEPTION_CALCULATION_JETALG_DISABLED=20497,//資料計算-JetAlg關閉
	AOI_EXCEPTION_CALCULATION_OPENCV_DISABLED=20498,//資料計算-OpenCV關閉
	AOI_EXCEPTION_CALCULATION_OTHERS        = 20499,//資料計算-錯誤訊息
	
	AOI_EXCEPTION_RETURN
};
//-------------------------------------------------------------------------------------//
#endif // !defined(AFX_AOIEXCEPTIONCODEDEF_H__2447BA75_1722_439F_A460_1CE9EC540916__INCLUDED_)
