#ifndef WND_ALG_PROPERTY_DEF_H_
#define WND_ALG_PROPERTY_DEF_H_
//-------------------------------------------------------------------------------------//
enum WND_GROUP_PROPERTY_ID
{
	WND_GROUP_PROPERTY_SCOPE_BEGIN,

	WND_GROUP_PROPERTY_MODEL_PARAM,
	WND_GROUP_PROPERTY_MODEL_EXTEND,
	WND_GROUP_PROPERTY_MODEL_EXTEND_X,
	WND_GROUP_PROPERTY_MODEL_EXTEND_Y,
	WND_GROUP_PROPERTY_MODEL_PARAM_END,

	WND_GROUP_PROPERTY_BODY_GROUP,
	WND_GROUP_PROPERTY_LAND_GROUP,
	WND_GROUP_PROPERTY_WND_GROUP,
	WND_GROUP_PROPERTY_LOGIC_GROUP,	
	WND_GROUP_PROPERTY_SCOPE_END
};
//-------------------------------------------------------------------------------------//
enum WND_OBJ_PROPERTY_ID
{
	WND_OBJ_PROPERTY_SCOPE_BEGIN,
	WND_OBJ_PROPERTY_ENABLE,
	WND_OBJ_PROPERTY_SCOPE_END
};
//-------------------------------------------------------------------------------------//
enum WND_ALG_PROPERTY_ID
{
	WND_ALG_PROPERTY_SCOPE_BEGIN,

	WND_ALG_PROPERTY_BASIC_BEGIN,	
	WND_ALG_PROPERTY_WND_DEFECT_ID,
	WND_ALG_PROPERTY_DEFECT_GROUP_ID,
	WND_ALG_PROPERTY_ALG_FRAME_ID,	
	WND_ALG_PROPERTY_MASK_FRAME_ID,	
	WND_ALG_PROPERTY_MASK_FUNC_MODE,
	WND_ALG_PROPERTY_WND_RGN_LINK_MODE,
	WND_ALG_PROPERTY_WND_RGN_LINK_RATIO_X,
	WND_ALG_PROPERTY_WND_RGN_LINK_RATIO_Y,
	WND_ALG_PROPERTY_EXTEND_RANGE,
	WND_ALG_PROPERTY_EXTEND_RANGE_X,
	WND_ALG_PROPERTY_EXTEND_RANGE_Y,	
	WND_ALG_PROPERTY_WND_RESULT_TEXT,
	WND_ALG_PROPERTY_MODEL_MASK,
	WND_ALG_PROPERTY_MODEL_MASK_PAD,
	WND_ALG_PROPERTY_MODEL_MASK_BODY,
	WND_ALG_PROPERTY_MODEL_MASK_BODY_NO_LEAD,
	WND_ALG_PROPERTY_MODEL_MASK_LEAD,
	WND_ALG_PROPERTY_MODEL_MASK_LEAD_TIP,
	WND_ALG_PROPERTY_MODEL_MASK_LEAD_SHOULDER,
	WND_ALG_PROPERTY_MODEL_MASK_CLEAR,
	WND_ALG_PROPERTY_BASIC_END,	

	WND_ALG_PROPERTY_PATTERN_MATCH_BEGIN,
	WND_ALG_PROPERTY_PATTERN_MATCH_OFFSET_X_USL,
	WND_ALG_PROPERTY_PATTERN_MATCH_OFFSET_X_LSL,
	WND_ALG_PROPERTY_PATTERN_MATCH_OFFSET_Y_USL,
	WND_ALG_PROPERTY_PATTERN_MATCH_OFFSET_Y_LSL,	
	WND_ALG_PROPERTY_PATTERN_MATCH_OFFSET_L_USL,
	WND_ALG_PROPERTY_PATTERN_MATCH_OFFSET_L_LSL, 
	WND_ALG_PROPERTY_PATTERN_MATCH_OFFSET_A_USL,
	WND_ALG_PROPERTY_PATTERN_MATCH_OFFSET_A_LSL,
	WND_ALG_PROPERTY_PATTERN_MATCH_SKEW_USL,
	WND_ALG_PROPERTY_PATTERN_MATCH_SKEW_LSL,
	WND_ALG_PROPERTY_PATTERN_MATCH_SCALE_NODE,
	WND_ALG_PROPERTY_PATTERN_MATCH_SCALE_ENABLE,
	WND_ALG_PROPERTY_PATTERN_MATCH_SCALE_USL,
	WND_ALG_PROPERTY_PATTERN_MATCH_SCALE_LSL,	
	WND_ALG_PROPERTY_PATTERN_MATCH_SIMILARITY_USL,
	WND_ALG_PROPERTY_PATTERN_MATCH_SIMILARITY_LSL,		
	WND_ALG_PROPERTY_PATTERN_MATCH_ANGLE_EXPAND,
	WND_ALG_PROPERTY_PATTERN_MATCH_SCALE_EXPAND,	
	WND_ALG_PROPERTY_PATTERN_MATCH_SCALE_ISOTROPIC,	
	WND_ALG_PROPERTY_PATTERN_MATCH_MIN_REDUCE_AREA,
	WND_ALG_PROPERTY_PATTERN_MATCH_FINAL_REDUCTION,	
	WND_ALG_PROPERTY_PATTERN_MATCH_ADVANCED_LEARNING,	
	WND_ALG_PROPERTY_PATTERN_MATCH_END,
	
	WND_ALG_PROPERTY_WND_ROI_BEGIN,
	WND_ALG_PROPERTY_WND_ROI_ADD,
	WND_ALG_PROPERTY_WND_ROI_DELETE,
	WND_ALG_PROPERTY_WND_ROI_CLEAR,
	WND_ALG_PROPERTY_WND_ROI_ADD_AUTO,
	WND_ALG_PROPERTY_WND_ROI_END,

	WND_ALG_PROPERTY_WND_MASK_BOX_BEGIN,
	WND_ALG_PROPERTY_WND_MASK_BOX_ADD,
	WND_ALG_PROPERTY_WND_MASK_BOX_ROTATE,
	WND_ALG_PROPERTY_WND_MASK_BOX_SHAPE_MODE,
	WND_ALG_PROPERTY_WND_MASK_BOX_SHAPE_PARAM_1,
	WND_ALG_PROPERTY_WND_MASK_BOX_SHAPE_PARAM_2,
	WND_ALG_PROPERTY_WND_MASK_BOX_DELETE,	
	WND_ALG_PROPERTY_WND_MASK_BOX_CLEAR,
	WND_ALG_PROPERTY_WND_MASK_BOX_END,

	WND_ALG_PROPERTY_ADVANCE_BEGIN,
	WND_ALG_PROPERTY_WND_LOGIC_GROUP,
	WND_ALG_PROPERTY_WND_LOGIC_TYPE,
	WND_ALG_PROPERTY_WND_LOGIC_GROUP_ID,
	WND_ALG_PROPERTY_ALG_BASE_VALUE_GROUP,
	WND_ALG_PROPERTY_ALG_BASE_VALUE_ENABLED,
	WND_ALG_PROPERTY_ALG_BASE_VALUE_GROUP_ID,
	WND_ALG_PROPERTY_ALG_SAVE_DEFECT_IMAGE,
	WND_ALG_PROPERTY_WND_FOLLOW_MODE,	
	WND_ALG_PROPERTY_WND_CONSTRAIN_MODE,
	WND_ALG_PROPERTY_WND_SYNC_MOVE_MODE,
	WND_ALG_PROPERTY_WND_CLASS_ID,
	WND_ALG_PROPERTY_WND_BOX_SHAPE_MODE,
	WND_ALG_PROPERTY_WND_BOX_SHAPE_PARAM_1,
	WND_ALG_PROPERTY_WND_BOX_SHAPE_PARAM_2,
	WND_ALG_PROPERTY_ADVANCE_END,

	WND_ALG_PROPERTY_RESULT_BEGIN,
	WND_ALG_PROPERTY_RESULT_END,	

	//Special Param - Bright Ratio	
	WND_ALG_PROPERTY_BRIGHT_RATIO_BEGIN,	
	WND_ALG_PROPERTY_BRIGHT_RATIO_TARGET_VALUE,		
	WND_ALG_PROPERTY_BRIGHT_RATIO_ROI_BOX_ENABLED, 
	WND_ALG_PROPERTY_BRIGHT_RATIO_AVERAGE_MODE,
	WND_ALG_PROPERTY_BRIGHT_RATIO_AVERAGE_PARTIAL_H,
	WND_ALG_PROPERTY_BRIGHT_RATIO_AVERAGE_PARTIAL_L,
	WND_ALG_PROPERTY_BRIGHT_RATIO_AVERAGE_SCALE_ENB,
	WND_ALG_PROPERTY_BRIGHT_RATIO_TOLERANCE_ENABLED,
	WND_ALG_PROPERTY_BRIGHT_RATIO_TOLERANCE_USL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_TOLERANCE_LSL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_LIMIT_GROUP,
	WND_ALG_PROPERTY_BRIGHT_RATIO_LIMIT_TOL_USL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_LIMIT_TOL_LSL,	
	WND_ALG_PROPERTY_BRIGHT_RATIO_LIMIT_MAX_ENABLED,
	WND_ALG_PROPERTY_BRIGHT_RATIO_LIMIT_MAX_SCALE_ENB,
	WND_ALG_PROPERTY_BRIGHT_RATIO_LIMIT_MIN_ENABLED,
	WND_ALG_PROPERTY_BRIGHT_RATIO_LIMIT_MIN_SCALE_ENB,
	WND_ALG_PROPERTY_BRIGHT_RATIO_RATIO_ENABLED,
	WND_ALG_PROPERTY_BRIGHT_RATIO_RATIO_AREA,
	WND_ALG_PROPERTY_BRIGHT_RATIO_RATIO_USL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_RATIO_LSL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_RANGE_ENABLED,
	WND_ALG_PROPERTY_BRIGHT_RATIO_RANGE_USL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_RANGE_LSL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_CONTRAST_ENABLED,
	WND_ALG_PROPERTY_BRIGHT_RATIO_CONTRAST_USL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_CONTRAST_LSL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_XLINE_ENABLED,
	WND_ALG_PROPERTY_BRIGHT_RATIO_XLINE_RANGE,
	WND_ALG_PROPERTY_BRIGHT_RATIO_XLINE_MODE,
	WND_ALG_PROPERTY_BRIGHT_RATIO_XLINE_UNIT_MODE,
	WND_ALG_PROPERTY_BRIGHT_RATIO_XLINE_USL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_XLINE_LSL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_YLINE_ENABLED,
	WND_ALG_PROPERTY_BRIGHT_RATIO_YLINE_RANGE,
	WND_ALG_PROPERTY_BRIGHT_RATIO_YLINE_MODE,
	WND_ALG_PROPERTY_BRIGHT_RATIO_YLINE_UNIT_MODE,
	WND_ALG_PROPERTY_BRIGHT_RATIO_YLINE_USL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_YLINE_LSL,
	WND_ALG_PROPERTY_BRIGHT_RATIO_END,	

	//Special Param - Outer Short
	WND_ALG_PROPERTY_OUTER_SHORT_BEGIN,
	WND_ALG_PROPERTY_OUTER_SHORT_ENABLED_R,
	WND_ALG_PROPERTY_OUTER_SHORT_RANGE_R,
	WND_ALG_PROPERTY_OUTER_SHORT_MODE_R,
	WND_ALG_PROPERTY_OUTER_SHORT_EXT_MODE_R,
	WND_ALG_PROPERTY_OUTER_SHORT_USL_R,
	WND_ALG_PROPERTY_OUTER_SHORT_LSL_R,
	WND_ALG_PROPERTY_OUTER_SHORT_APPLY_R,
	WND_ALG_PROPERTY_OUTER_SHORT_ENABLED_T,	
	WND_ALG_PROPERTY_OUTER_SHORT_RANGE_T,
	WND_ALG_PROPERTY_OUTER_SHORT_MODE_T,
	WND_ALG_PROPERTY_OUTER_SHORT_EXT_MODE_T,
	WND_ALG_PROPERTY_OUTER_SHORT_USL_T,
	WND_ALG_PROPERTY_OUTER_SHORT_LSL_T,	
	WND_ALG_PROPERTY_OUTER_SHORT_APPLY_T,
	WND_ALG_PROPERTY_OUTER_SHORT_ENABLED_L,
	WND_ALG_PROPERTY_OUTER_SHORT_RANGE_L,
	WND_ALG_PROPERTY_OUTER_SHORT_MODE_L,
	WND_ALG_PROPERTY_OUTER_SHORT_EXT_MODE_L,
	WND_ALG_PROPERTY_OUTER_SHORT_USL_L,
	WND_ALG_PROPERTY_OUTER_SHORT_LSL_L,	
	WND_ALG_PROPERTY_OUTER_SHORT_APPLY_L,
	WND_ALG_PROPERTY_OUTER_SHORT_ENABLED_B,
	WND_ALG_PROPERTY_OUTER_SHORT_RANGE_B,
	WND_ALG_PROPERTY_OUTER_SHORT_MODE_B,
	WND_ALG_PROPERTY_OUTER_SHORT_EXT_MODE_B,
	WND_ALG_PROPERTY_OUTER_SHORT_USL_B,
	WND_ALG_PROPERTY_OUTER_SHORT_LSL_B,
	WND_ALG_PROPERTY_OUTER_SHORT_APPLY_B,
	WND_ALG_PROPERTY_OUTER_SHORT_END,	
	
	//Special Param - Bright Blob
	WND_ALG_PROPERTY_BLOB_BEGIN,	
	WND_ALG_PROPERTY_BLOB_X_SIZE_MAX,
	WND_ALG_PROPERTY_BLOB_X_SIZE_MIN,	
	WND_ALG_PROPERTY_BLOB_Y_SIZE_MAX,
	WND_ALG_PROPERTY_BLOB_Y_SIZE_MIN,
	WND_ALG_PROPERTY_BLOB_L_SIZE_MAX,
	WND_ALG_PROPERTY_BLOB_L_SIZE_MIN,
	WND_ALG_PROPERTY_BLOB_AREA_SIZE_MAX,
	WND_ALG_PROPERTY_BLOB_AREA_SIZE_MIN,
	WND_ALG_PROPERTY_BLOB_ASPECT_RATIO_MAX,
	WND_ALG_PROPERTY_BLOB_ASPECT_RATIO_MIN,
	WND_ALG_PROPERTY_BLOB_FILL_RATIO_MAX,
	WND_ALG_PROPERTY_BLOB_FILL_RATIO_MIN,
	WND_ALG_PROPERTY_BLOB_LONG_SHORT_RATIO_MAX,
	WND_ALG_PROPERTY_BLOB_LONG_SHORT_RATIO_MIN,
	WND_ALG_PROPERTY_BLOB_CONNECTIVITY,
	WND_ALG_PROPERTY_BLOB_ROI_SHRINK_X,	
	WND_ALG_PROPERTY_BLOB_ROI_SHRINK_Y,		
	WND_ALG_PROPERTY_BLOB_COUNT_USL,
	WND_ALG_PROPERTY_BLOB_COUNT_LSL,	
	WND_ALG_PROPERTY_BLOB_DETAIL_SET,
	WND_ALG_PROPERTY_BLOB_END,	

	//Special Param - Body Tilt
	WND_ALG_PROPERTY_TILT_BEGIN,
	WND_ALG_PROPERTY_TILT_SIZE_RATIO_X,
	WND_ALG_PROPERTY_TILT_SIZE_RATIO_Y,
	WND_ALG_PROPERTY_TILT_CELL_MODE,
	WND_ALG_PROPERTY_TILT_GAP_USL,
	WND_ALG_PROPERTY_TILT_GAP_LSL,
	WND_ALG_PROPERTY_TILT_ANGLE_USL,
	WND_ALG_PROPERTY_TILT_ANGLE_LSL,
	WND_ALG_PROPERTY_TILT_END,

	//Special Param - Barcode Recognize
	WND_ALG_PROPERTY_BARCODE_BEGIN,
	WND_ALG_PROPERTY_BARCODE_ENABLE_BEGIN,
	WND_ALG_PROPERTY_BARCODE_1D_ENABLED,
	WND_ALG_PROPERTY_BARCODE_QRCODE_ENABLED,
	WND_ALG_PROPERTY_BARCODE_DATA_MATRIX_ENABLED,

	WND_ALG_PROPERTY_BARCODE_1D_DECODER,
	WND_ALG_PROPERTY_BARCODE_QRCODE_DECODER,
	WND_ALG_PROPERTY_BARCODE_DATA_MATRIX_DECODER,

	WND_ALG_PROPERTY_BARCODE_DECODE_TIMEOUT,
	WND_ALG_PROPERTY_BARCODE_DECODE_START_STEP,
	WND_ALG_PROPERTY_BARCODE_DIRECTION_MODE,
	WND_ALG_PROPERTY_BARCODE_CODE_COUNT,	
	WND_ALG_PROPERTY_BARCODE_CODE_CONTENT,
	WND_ALG_PROPERTY_BARCODE_CODE_CONTENT_ENABLE,
	WND_ALG_PROPERTY_BARCODE_CODE_JSON_CHECK_ENABLE,
	WND_ALG_PROPERTY_BARCODE_CHECK_SUM_ENABLE,
	WND_ALG_PROPERTY_BARCODE_CODE_RESULT,
	WND_ALG_PROPERTY_BARCODE_VERIFY_USL,
	WND_ALG_PROPERTY_BARCODE_VERIFY_LSL,	
	WND_ALG_PROPERTY_BARCODE_SETUP_BTN,	

	WND_ALG_PROPERTY_BARCODE_DECODE_STEP_1,
	WND_ALG_PROPERTY_BARCODE_DECODE_NAME_1,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM1_1,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM2_1,
	WND_ALG_PROPERTY_BARCODE_DECODE_ENABLE_1,
	WND_ALG_PROPERTY_BARCODE_DECODE_DECODED_1,

	WND_ALG_PROPERTY_BARCODE_DECODE_STEP_2,
	WND_ALG_PROPERTY_BARCODE_DECODE_NAME_2,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM1_2,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM2_2,
	WND_ALG_PROPERTY_BARCODE_DECODE_ENABLE_2,
	WND_ALG_PROPERTY_BARCODE_DECODE_DECODED_2,

	WND_ALG_PROPERTY_BARCODE_DECODE_STEP_3,
	WND_ALG_PROPERTY_BARCODE_DECODE_NAME_3,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM1_3,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM2_3,
	WND_ALG_PROPERTY_BARCODE_DECODE_ENABLE_3,
	WND_ALG_PROPERTY_BARCODE_DECODE_DECODED_3,

	WND_ALG_PROPERTY_BARCODE_DECODE_STEP_4,
	WND_ALG_PROPERTY_BARCODE_DECODE_NAME_4,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM1_4,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM2_4,
	WND_ALG_PROPERTY_BARCODE_DECODE_ENABLE_4,
	WND_ALG_PROPERTY_BARCODE_DECODE_DECODED_4,

	WND_ALG_PROPERTY_BARCODE_DECODE_STEP_5,
	WND_ALG_PROPERTY_BARCODE_DECODE_NAME_5,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM1_5,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM2_5,
	WND_ALG_PROPERTY_BARCODE_DECODE_ENABLE_5,
	WND_ALG_PROPERTY_BARCODE_DECODE_DECODED_5,

	WND_ALG_PROPERTY_BARCODE_DECODE_STEP_6,
	WND_ALG_PROPERTY_BARCODE_DECODE_NAME_6,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM1_6,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM2_6,
	WND_ALG_PROPERTY_BARCODE_DECODE_ENABLE_6,
	WND_ALG_PROPERTY_BARCODE_DECODE_DECODED_6,

	WND_ALG_PROPERTY_BARCODE_DECODE_STEP_7,
	WND_ALG_PROPERTY_BARCODE_DECODE_NAME_7,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM1_7,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM2_7,
	WND_ALG_PROPERTY_BARCODE_DECODE_ENABLE_7,
	WND_ALG_PROPERTY_BARCODE_DECODE_DECODED_7,

	WND_ALG_PROPERTY_BARCODE_DECODE_STEP_8,
	WND_ALG_PROPERTY_BARCODE_DECODE_NAME_8,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM1_8,
	WND_ALG_PROPERTY_BARCODE_DECODE_PARAM2_8,
	WND_ALG_PROPERTY_BARCODE_DECODE_ENABLE_8,
	WND_ALG_PROPERTY_BARCODE_DECODE_DECODED_8,

	WND_ALG_PROPERTY_BARCODE_END,	

	//Special Param - Object Measure
	WND_ALG_PROPERTY_OBJECT_MEASURE_BEGIN,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SPEC_SETTING,
	WND_ALG_PROPERTY_OBJECT_MEASURE_USE_MULTI_BLOB,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_CALC_MODE,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_CALC_UNIT_MODE,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_BLUR_PARAM,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_X_ENB,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_X_SPEC,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_X_READING,	
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_X_DIFF_USL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_X_DIFF_LSL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_X_RATIO_USL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_X_RATIO_LSL,

	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_Y_ENB,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_Y_SPEC,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_Y_READING,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_Y_DIFF_USL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_Y_DIFF_LSL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_Y_RATIO_USL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_SIZE_Y_RATIO_LSL,

	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_ENB,
	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_SPEC,
	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_AVE_MODE,
	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_AVE_PARTIAL_USL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_AVE_PARTIAL_LSL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_READING,
	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_CALC_UNIT_MODE,
	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_DIFF_USL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_DIFF_LSL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_RATIO_USL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_HEIGHT_RATIO_LSL,

	WND_ALG_PROPERTY_OBJECT_MEASURE_AREA_ENB,
	WND_ALG_PROPERTY_OBJECT_MEASURE_AREA_SPEC,
	WND_ALG_PROPERTY_OBJECT_MEASURE_AREA_READING,
	WND_ALG_PROPERTY_OBJECT_MEASURE_AREA_RATIO_USL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_AREA_RATIO_LSL,

	WND_ALG_PROPERTY_OBJECT_MEASURE_VOLUME_ENB,
	WND_ALG_PROPERTY_OBJECT_MEASURE_VOLUME_SPEC,
	WND_ALG_PROPERTY_OBJECT_MEASURE_VOLUME_READING,
	WND_ALG_PROPERTY_OBJECT_MEASURE_VOLUME_RATIO_USL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_VOLUME_RATIO_LSL,
	WND_ALG_PROPERTY_OBJECT_MEASURE_END,

	//Special Param - Model Match		
	WND_ALG_PROPERTY_MODEL_MATCH_BEGIN,		
	WND_ALG_PROPERTY_MODEL_MATCH_DOCK_MODE,	
	WND_ALG_PROPERTY_MODEL_MATCH_RECHECK_BOX,	
	WND_ALG_PROPERTY_MODEL_MATCH_END,

	//Special Param - Image Match		
	WND_ALG_PROPERTY_IMAGE_MATCH_BEGIN,
	WND_ALG_PROPERTY_IMAGE_MATCH_POLARITY,	
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_ENABLED,
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_DARK_LEVEL,
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_TOLERANCE,
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_GAUSSIAN_SIZE,
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_OPEN_SIZE,
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_CLOSE_SIZE,
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_X_SIZE_MIN,
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_Y_SIZE_MIN,
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_AREA_MIN,
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_COUNT_USL,
	WND_ALG_PROPERTY_IMAGE_MATCH_PXL_CMP_COUNT_LSL,	
	WND_ALG_PROPERTY_IMAGE_MATCH_END,

	//Special Param - Char Verify	
	WND_ALG_PROPERTY_CHAR_VERIFY_BEGIN,	
	WND_ALG_PROPERTY_CHAR_VERIFY_POLARITY,
	WND_ALG_PROPERTY_CHAR_VERIFY_CELL_LEVEL,
	WND_ALG_PROPERTY_CHAR_VERIFY_CELL_EXT_SIZE,
	WND_ALG_PROPERTY_CHAR_VERIFY_CELL_SCORE_MAX,
	WND_ALG_PROPERTY_CHAR_VERIFY_CELL_SCORE_MIN,	
	WND_ALG_PROPERTY_CHAR_VERIFY_PASS_RATIO_USL,
	WND_ALG_PROPERTY_CHAR_VERIFY_PASS_RATIO_LSL,
	WND_ALG_PROPERTY_CHAR_VERIFY_END,	

	//Special Param - Color Code
	WND_ALG_PROPERTY_COLOR_CODE_BEGIN,	
	WND_ALG_PROPERTY_COLOR_CODE_POLARITY,
	WND_ALG_PROPERTY_COLOR_CODE_CELL_SCORE_MAX,
	WND_ALG_PROPERTY_COLOR_CODE_CELL_SCORE_MIN,	
	WND_ALG_PROPERTY_COLOR_CODE_PASS_RATIO_USL,
	WND_ALG_PROPERTY_COLOR_CODE_PASS_RATIO_LSL,
	WND_ALG_PROPERTY_COLOR_CODE_END,	

	//Special Param - Fd Match		
	WND_ALG_PROPERTY_FD_MATCH_BEGIN,
	WND_ALG_PROPERTY_FD_MATCH_MODE,
	WND_ALG_PROPERTY_FD_FILL_SIZE,
	WND_ALG_PROPERTY_FD_MATCH_END,

	//Special Param - Edge Search
	WND_ALG_PROPERTY_EDGE_SEARCH_BEGIN,
	WND_ALG_PROPERTY_EDGE_SEARCH_CUT_LINE_ENB,
	WND_ALG_PROPERTY_EDGE_SEARCH_INVERT_ALIGN,	

	WND_ALG_PROPERTY_EDGE_SEARCH_ENABLE_F,	
	WND_ALG_PROPERTY_EDGE_SEARCH_SIZE_CALC_MODE_F,
	WND_ALG_PROPERTY_EDGE_SEARCH_SEARCH_DIRECTION_F,
	WND_ALG_PROPERTY_EDGE_SEARCH_MIN_RATIO_U_F,
	WND_ALG_PROPERTY_EDGE_SEARCH_MAX_RATIO_U_F,
	WND_ALG_PROPERTY_EDGE_SEARCH_MIN_RANGE_V_F,
	WND_ALG_PROPERTY_EDGE_SEARCH_MAX_RANGE_V_F,
	WND_ALG_PROPERTY_EDGE_SEARCH_SIZE_RATIO_V_F,		
	WND_ALG_PROPERTY_EDGE_SEARCH_FIND_RATIO_V_F,		

	WND_ALG_PROPERTY_EDGE_SEARCH_ENABLE_B,	
	WND_ALG_PROPERTY_EDGE_SEARCH_SIZE_CALC_MODE_B,
	WND_ALG_PROPERTY_EDGE_SEARCH_SEARCH_DIRECTION_B,
	WND_ALG_PROPERTY_EDGE_SEARCH_MIN_RATIO_U_B,
	WND_ALG_PROPERTY_EDGE_SEARCH_MAX_RATIO_U_B,
	WND_ALG_PROPERTY_EDGE_SEARCH_MIN_RANGE_V_B,
	WND_ALG_PROPERTY_EDGE_SEARCH_MAX_RANGE_V_B,
	WND_ALG_PROPERTY_EDGE_SEARCH_SIZE_RATIO_V_B,
	WND_ALG_PROPERTY_EDGE_SEARCH_FIND_RATIO_V_B,
	WND_ALG_PROPERTY_EDGE_SEARCH_END,

	WND_ALG_PROPERTY_SHAPE_VERIFY_BEGIN,	
	WND_ALG_PROPERTY_SHAPE_VERIFY_KEEP_COUNT,
	WND_ALG_PROPERTY_SHAPE_VERIFY_FILL_SIZE,	
	WND_ALG_PROPERTY_SHAPE_VERIFY_SKIP_RATIO_INNER,
	WND_ALG_PROPERTY_SHAPE_VERIFY_SKIP_RATIO_OUTER,
	WND_ALG_PROPERTY_SHAPE_VERIFY_RESULT,
	WND_ALG_PROPERTY_SHAPE_VERIFY_OUTER_TOL,
	WND_ALG_PROPERTY_SHAPE_VERIFY_INNER_TOL,
	WND_ALG_PROPERTY_SHAPE_VERIFY_RANGE_TOL,
	WND_ALG_PROPERTY_SHAPE_VERIFY_ERROR_TOL,	
	WND_ALG_PROPERTY_SHAPE_VERIFY_END,

	//Special Param - Angle Measure
	WND_ALG_PROPERTY_ANGLE_MEASURE_BEGIN,
	WND_ALG_PROPERTY_ANGLE_MEASURE_ANGLE_MODE,
	WND_ALG_PROPERTY_ANGLE_MEASURE_BASE_LINE_MODE,
	WND_ALG_PROPERTY_ANGLE_MEASURE_ANGLE_SPEC,
	WND_ALG_PROPERTY_ANGLE_MEASURE_TOLERANCE_USL,
	WND_ALG_PROPERTY_ANGLE_MEASURE_TOLERANCE_LSL,	
	WND_ALG_PROPERTY_ANGLE_MEASURE_END,

	//Special Param - Pixel Compare
	WND_ALG_PROPERTY_PIXEL_COMPARE_BEGIN,		
	WND_ALG_PROPERTY_PIXEL_COMPARE_CELL_EXT_SIZE,	

	WND_ALG_PROPERTY_PIXEL_COMPARE_IMG_BLUR_SIZE,
	WND_ALG_PROPERTY_PIXEL_COMPARE_PAT_SCOPE,	
	WND_ALG_PROPERTY_PIXEL_COMPARE_PAT_LIGHT_LEVEL,
	WND_ALG_PROPERTY_PIXEL_COMPARE_PAT_DARK_LEVEL,	
	WND_ALG_PROPERTY_PIXEL_COMPARE_PAT_ERODE_SIZE,
	WND_ALG_PROPERTY_PIXEL_COMPARE_PAT_PURE_COLOR,

	WND_ALG_PROPERTY_PIXEL_COMPARE_CMP_SCOPE,
	WND_ALG_PROPERTY_PIXEL_COMPARE_CMP_LIGHT_GAIN,
	WND_ALG_PROPERTY_PIXEL_COMPARE_CMP_DARK_GAIN,	
	WND_ALG_PROPERTY_PIXEL_COMPARE_CMP_TOLERANCE,
	WND_ALG_PROPERTY_PIXEL_COMPARE_CMP_GAUSSIAN_SIZE,
	WND_ALG_PROPERTY_PIXEL_COMPARE_CMP_OPEN_SIZE,
	WND_ALG_PROPERTY_PIXEL_COMPARE_CMP_CLOSE_SIZE,

	WND_ALG_PROPERTY_PIXEL_COMPARE_BLOB_MIN_SIZE_D,
	WND_ALG_PROPERTY_PIXEL_COMPARE_BLOB_MIN_H,
	WND_ALG_PROPERTY_PIXEL_COMPARE_BLOB_MIN_AREA,

	WND_ALG_PROPERTY_PIXEL_COMPARE_BLOB_COUNT_USL,
	WND_ALG_PROPERTY_PIXEL_COMPARE_BLOB_COUNT_LSL,
	WND_ALG_PROPERTY_PIXEL_COMPARE_END,	
	
	//Special Param - Group Compare
	WND_ALG_PROPERTY_GROUP_COMPARE_BEGIN,
	WND_ALG_PROPERTY_GROUP_COMPARE_DIR_MODE,
	WND_ALG_PROPERTY_GROUP_COMPARE_2D_GRAY_ENABLED,
	WND_ALG_PROPERTY_GROUP_COMPARE_2D_GRAY_USL,
	WND_ALG_PROPERTY_GROUP_COMPARE_2D_GRAY_LSL,
	WND_ALG_PROPERTY_GROUP_COMPARE_3D_HEIGHT_ENABLED,
	WND_ALG_PROPERTY_GROUP_COMPARE_3D_HEIGHT_BASE_MODE,	
	WND_ALG_PROPERTY_GROUP_COMPARE_3D_HEIGHT_USL,
	WND_ALG_PROPERTY_GROUP_COMPARE_3D_HEIGHT_LSL,
	WND_ALG_PROPERTY_GROUP_COMPARE_TILT_ANGLE_ENABLED,
	WND_ALG_PROPERTY_GROUP_COMPARE_TILT_ANGLE_USL,
	WND_ALG_PROPERTY_GROUP_COMPARE_TILT_ANGLE_LSL,
	WND_ALG_PROPERTY_GROUP_COMPARE_END,
	
	WND_ALG_PROPERTY_IPC_BEGIN,
	WND_ALG_PROPERTY_IPC_CONTINUOUS_SET,
	WND_ALG_PROPERTY_IPC_WIDTH_GAP,
	WND_ALG_PROPERTY_IPC_WIDTH_RATIO,
	//WND_ALG_PROPERTY_BLOB_WIDTH_SIZE,
	WND_ALG_PROPERTY_IPC_NODE,
	WND_ALG_PROPERTY_IPC_ENABLED,
	WND_ALG_PROPERTY_IPC_XVALUE,
	WND_ALG_PROPERTY_IPC_YVALUE,
	WND_ALG_PROPERTY_IPC_END,

	WND_ALG_PROPERTY_RESIN_BEGIN,
	WND_ALG_PROPERTY_RESIN_ENABLED,
	WND_ALG_PROPERTY_RESIN_NG_CHECK,
	WND_ALG_PROPERTY_RESIN_TYPE,
	WND_ALG_PROPERTY_RESIN_OUTPUT_TYPE,
	WND_ALG_PROPERTY_RESIN_DIRECTION,
	WND_ALG_PROPERTY_RESIN_RANGE,
	WND_ALG_PROPERTY_RESIN_STEP_Z,
	WND_ALG_PROPERTY_RESIN_SHIFT,
	WND_ALG_PROPERTY_RESIN_THRESHOLD_WIDTH, 
	WND_ALG_PROPERTY_RESIN_THRESHOLD_HEIGHT,
	WND_ALG_PROPERTY_RESIN_HEIGHT_MEASURE_MODE,
	WND_ALG_PROPERTY_RESIN_HEIGHT_VALUE,
	WND_ALG_PROPERTY_RESIN_END,

	WND_ALG_PROPERTY_AIMODEL_BEGIN,
	WND_ALG_PROPERTY_AIMODEL_AI_MODEL_ID,
	WND_ALG_PROPERTY_AIMODEL_PATTERN_ANGLE,
	WND_ALG_PROPERTY_AIMODEL_CONFIDENCE_THRESHOLD,
	WND_ALG_PROPERTY_AIMODEL_CHAR_MATCH_NUM_THRESHOLD,
	WND_ALG_PROPERTY_AIMODEL_CHAR_NUM_UPPER_THRESHOLD,
	WND_ALG_PROPERTY_AIMODEL_END,

	//Special Param - Solder Wetting
	WND_ALG_PROPERTY_SOLDER_WETTING_BEGIN,		
	WND_ALG_PROPERTY_SOLDER_WETTING_CIRCLE_ANGLE_ENABLED,
	WND_ALG_PROPERTY_SOLDER_WETTING_CIRCLE_ANGLE_USL,
	WND_ALG_PROPERTY_SOLDER_WETTING_CIRCLE_ANGLE_LSL,
	WND_ALG_PROPERTY_SOLDER_WETTING_CIRCLE_ANGLE_LINE_START_RATIO,
	WND_ALG_PROPERTY_SOLDER_WETTING_CIRCLE_ANGLE_LINE_PASS_RATIO,
	WND_ALG_PROPERTY_SOLDER_WETTING_CIRCLE_ANGLE_READING,
	WND_ALG_PROPERTY_SOLDER_WETTING_SETUP_BTN,
	WND_ALG_PROPERTY_SOLDER_WETTING_END,

	WND_ALG_PROPERTY_WIRE_WIDTH_BEGIN,
	WND_ALG_PROPERTY_WIRE_WIDTH_FILTER_ENABLED,
	WND_ALG_PROPERTY_WIRE_WIDTH_FILTER_SIZE,
	WND_ALG_PROPERTY_WIRE_WIDTH_EDGE_LOW_THRESHOLD,
	WND_ALG_PROPERTY_WIRE_WIDTH_EDGE_HIGHT_THRESHOLD,
	WND_ALG_PROPERTY_WIRE_WIDTH_VALUE_USL,
	WND_ALG_PROPERTY_WIRE_WIDTH_VALUE_LSL,
	WND_ALG_PROPERTY_WIRE_WIDTH_END,

	//Special Param - Measure Black Glue
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_BEGIN,
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_FRAME_ID_01,
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_FRAME_ID_02,
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_FRAME_ID_03,
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_FRAME_ID_04,
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_SETUP_BTN,
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_EDGE,//板邊偵測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_GLUE_EDGE,//膠邊偵測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_EDGE,//Coating偵測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_START_END,//膠首尾距離量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_START_DIST_USL,//膠首尾距離量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_START_DIST_LSL,//膠首尾距離量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_HOR,//水平膠寬量測結果	
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_HOR_DIST_MAX_USL,//水平膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_HOR_DIST_MAX_LSL,//水平膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_HOR_DIST_MIN_USL,//水平膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_HOR_DIST_MIN_LSL,//水平膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_HOR_DIST_DIF_USL,//水平膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_HOR_DIST_DIF_LSL,//水平膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_VER,//垂直膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_VER_DIST_MAX_USL,//垂直膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_VER_DIST_MAX_LSL,//垂直膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_VER_DIST_MIN_USL,//垂直膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_VER_DIST_MIN_LSL,//垂直膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_VER_DIST_DIF_USL,//垂直膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_WIDTH_VER_DIST_DIF_LSL,//垂直膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_HOR,//水平方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_HOR_DIST_MAX_USL,//水平方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_HOR_DIST_MAX_LSL,//水平方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_HOR_DIST_MIN_USL,//水平方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_HOR_DIST_MIN_LSL,//水平方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_HOR_DIST_DIF_USL,//水平方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_HOR_DIST_DIF_LSL,//水平方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_VER,//垂直方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_VER_DIST_MAX_USL,//垂直方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_VER_DIST_MAX_LSL,//垂直方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_VER_DIST_MIN_USL,//垂直方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_VER_DIST_MIN_LSL,//垂直方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_VER_DIST_DIF_USL,//垂直方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_BOARD_TO_GLUE_VER_DIST_DIF_LSL,//垂直方向板邊到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_HOR,//水平方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_HOR_DIST_MAX_USL,//水平方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_HOR_DIST_MAX_LSL,//水平方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_HOR_DIST_MIN_USL,//水平方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_HOR_DIST_MIN_LSL,//水平方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_HOR_DIST_DIF_USL,//水平方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_HOR_DIST_DIF_LSL,//水平方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_VER,//垂直方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_VER_DIST_MAX_USL,//垂直方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_VER_DIST_MAX_LSL,//垂直方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_VER_DIST_MIN_USL,//垂直方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_VER_DIST_MIN_LSL,//垂直方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_VER_DIST_DIF_USL,//垂直方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_COATING_TO_GLUE_VER_DIST_DIF_LSL,//垂直方向Coating到膠邊量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_ARC,//弧線膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_ARC_DIST_MAX_USL,//弧線膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_ARC_DIST_MAX_LSL,//弧線膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_ARC_DIST_MIN_USL,//弧線膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_ARC_DIST_MIN_LSL,//弧線膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_ARC_DIST_DIF_USL,//弧線膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_ARC_DIST_DIF_LSL,//弧線膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_WIDTH,//散熱膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_WIDTH_DIST_MAX_USL,//散熱膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_WIDTH_DIST_MAX_LSL,//散熱膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_WIDTH_DIST_MIN_USL,//散熱膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_WIDTH_DIST_MIN_LSL,//散熱膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_WIDTH_DIST_DIF_USL,//散熱膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_WIDTH_DIST_DIF_LSL,//散熱膠寬量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_GLUE,//散熱膠到膠量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_GLUE_DIST_MAX_USL,//散熱膠到膠量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_GLUE_DIST_MAX_LSL,//散熱膠到膠量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_GLUE_DIST_MIN_USL,//散熱膠到膠量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_GLUE_DIST_MIN_LSL,//散熱膠到膠量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_GLUE_DIST_DIF_USL,//散熱膠到膠量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_GLUE_DIST_DIF_LSL,//散熱膠到膠量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_DIE,//散熱膠到Die量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_DIE_DIST_MAX_USL,//散熱膠到Die量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_DIE_DIST_MAX_LSL,//散熱膠到Die量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_DIE_DIST_MIN_USL,//散熱膠到Die量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_DIE_DIST_MIN_LSL,//散熱膠到Die量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_DIE_DIST_DIF_USL,//散熱膠到Die量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_RESULT_THERMAL_TO_DIE_DIST_DIF_LSL,//散熱膠到Die量測結果
	WND_ALG_PROPERTY_MEASURE_BLACK_GLUE_END,

	//Special Param - Measure Flux Area
	WND_ALG_PROPERTY_MEASURE_FLUX_AREA_BEGIN,
	WND_ALG_PROPERTY_MEASURE_FLUX_AREA_FRAME_ID_01,
	WND_ALG_PROPERTY_MEASURE_FLUX_AREA_SETUP_BTN,
	WND_ALG_PROPERTY_MEASURE_FLUX_AREA_END,

	//Special Param - Measure CPU Pin
	WND_ALG_PROPERTY_MEASURE_CPU_PIN_BEGIN,
	WND_ALG_PROPERTY_MEASURE_CPU_PIN_FRAME_ID_01,
	WND_ALG_PROPERTY_MEASURE_CPU_PIN_SETUP_BTN,
	WND_ALG_PROPERTY_MEASURE_CPU_PIN_END,

	WND_ALG_PROPERTY_MEASURE_SIP_BEGIN,
	WND_ALG_PROPERTY_MEASURE_SIP_DIRECTION,
	WND_ALG_PROPERTY_MEASURE_SIP_INSPEC_EDGE_COUNT,
	WND_ALG_PROPERTY_MEASURE_SIP_REF_EDGE_COUNT,
	WND_ALG_PROPERTY_MEASURE_SIP_ANGLE_SPEC,
	WND_ALG_PROPERTY_MEASURE_SIP_ANGLE_TOLERANCE_USL,
	WND_ALG_PROPERTY_MEASURE_SIP_ANGLE_TOLERANCE_LSL,
	WND_ALG_PROPERTY_MEASURE_SIP_DISTANCE_TO_A_SPEC,
	WND_ALG_PROPERTY_MEASURE_SIP_DISTANCE_TO_A_TOLERANCE_USL,
	WND_ALG_PROPERTY_MEASURE_SIP_DISTANCE_TO_A_TOLERANCE_LSL,
	WND_ALG_PROPERTY_MEASURE_SIP_DISTANCE_TO_B_SPEC,
	WND_ALG_PROPERTY_MEASURE_SIP_DISTANCE_TO_B_TOLERANCE_USL,
	WND_ALG_PROPERTY_MEASURE_SIP_DISTANCE_TO_B_TOLERANCE_LSL,
	WND_ALG_PROPERTY_MEASURE_SIP_END,

	WND_ALG_PROPERTY_MEASURE_CONNECTOR_BEGIN,
	WND_ALG_PROPERTY_MEASURE_CONNECTOR_IMPORT,
	WND_ALG_PROPERTY_MEASURE_CONNECTOR_RESULT,
	//Todo-Alan
	WND_ALG_PROPERTY_MEASURE_CONNECTOR_END,
	WND_ALG_PROPERTY_SCOPE_END
};
//-------------------------------------------------------------------------------------//
typedef struct _WND_PARAM_CHANGED_RESULT
{
	bool               bReBuildWndUI;
	bool               bParamChanged;
	bool               bWndRgnChanged;
	bool               bFrameIndexChagned;	
	CString            sValueName;//變更項目
	CString            sValueOld;//舊的數值
	CString            sValueNew;//新的數值
	_WND_PARAM_CHANGED_RESULT()
	{
		bReBuildWndUI=true;
		bParamChanged=false;
		bWndRgnChanged=false;
		bFrameIndexChagned=false;

		sValueName = _T("");
		sValueOld = _T("");
		sValueNew = _T("");
	}
} TWND_PARAM_CHANGED_RESULT, *PWND_PARAM_CHANGED_RESULT;
//-------------------------------------------------------------------------------------//
typedef struct _PROP_GRID_PARAM
{
	bool bGeneral_WndRoiExpand;	
	bool bGeneral_RgnLinkExpand;	
	bool bGeneral_BoxMaskExpand;
	bool bGeneral_AIModelExpand;
	bool bGeneral_ModelMaskExpand;	
	bool bGeneral_WndLogicExpand;
	bool bGeneral_ExtendRangeExpand;		

	bool bPattern_ScaleScopeExpand;

	bool bBrightRatio_ToleranceExpand;
	bool bBrightRatio_RatioExpand;
	bool bBrightRatio_RangeExpand;
	bool bBrightRatio_ContrastExpand;
	bool bBrightRatio_ThroughXExpand;
	bool bBrightRatio_ThroughYExpand;

	bool bOuterShort_LeftExpand;
	bool bOuterShort_UpExpand;
	bool bOuterShort_RightExpand;
	bool bOuterShort_DowndExpand;

	bool bPixelCompare_PatScopeExpand;
	bool bPixelCompare_CmpScopeExpand;

	bool bWndCompare_ROIExpand;
	void SetExpand(bool bExpand)
	{
		bGeneral_WndRoiExpand = bExpand;
		bGeneral_RgnLinkExpand = bExpand;
		bGeneral_BoxMaskExpand = bExpand;
		bGeneral_AIModelExpand = bExpand;
		bGeneral_ModelMaskExpand = bExpand;
		bGeneral_WndLogicExpand = bExpand;
		bGeneral_ExtendRangeExpand = bExpand;

		bPattern_ScaleScopeExpand = bExpand;

		bBrightRatio_ToleranceExpand = bExpand;
		bBrightRatio_RatioExpand = bExpand;
		bBrightRatio_RangeExpand = bExpand;
		bBrightRatio_ContrastExpand = bExpand;
		bBrightRatio_ThroughXExpand = bExpand;
		bBrightRatio_ThroughYExpand = bExpand;

		bOuterShort_LeftExpand = bExpand;
		bOuterShort_UpExpand = bExpand;
		bOuterShort_RightExpand = bExpand;
		bOuterShort_DowndExpand = bExpand;	

		bPixelCompare_PatScopeExpand = bExpand;
		bPixelCompare_CmpScopeExpand = bExpand;

		bWndCompare_ROIExpand = bExpand;
	}
} TPropGridParam, *PPropGridParam;
//-------------------------------------------------------------------------------------//
#endif//WND_ALG_PROPERTY_DEF_H_