#ifndef _Barcode_Define_H_
#define _Barcode_Define_H_
//-------------------------------------------------------------------------------------//
#ifndef BARCODE_SIZE
	#define BARCODE_SIZE 128
#endif//BARCODE_SIZE
#define   BARCODE_SUB_COUNT      64//兵絏甧秖へ
//-------------------------------------------------------------------------------------//
#define MAX_BARCODE_DEVICE_COUNT         8//程8兵絏杆竚
#define MAX_BARCODE_DEVICE_CODE_COUNT   BARCODE_SUB_COUNT//程10兵絏
#define MAX_BARCODE_DEVICE_RECEIVE_SIZE 4096//程4096じ计
//-------------------------------------------------------------------------------------//
#define BARCODE_DEVICE_ID_OFF            0
#define BARCODE_DEVICE_ID_01             1
#define BARCODE_DEVICE_ID_02             2
#define BARCODE_DEVICE_ID_03             3
#define BARCODE_DEVICE_ID_04             4
#define BARCODE_DEVICE_ID_05             5
#define BARCODE_DEVICE_ID_06             6
#define BARCODE_DEVICE_ID_07             7
#define BARCODE_DEVICE_ID_08             8
//-------------------------------------------------------------------------------------//
enum BARCODE_DEVICE_TYPE
{	
	BARCODE_DEVICE_NULL                =    0,

	BARCODE_DEVICE_MICROSCAN_GROUP     = 100,
	BARCODE_DEVICE_MICROSCAN_MS3,
	BARCODE_DEVICE_MICROSCAN_MINI,
	BARCODE_DEVICE_MICROSCAN_MINI_VELOCITY,
	BARCODE_DEVICE_MICROSCAN_MINI3,
	BARCODE_DEVICE_MICROSCAN_MINI_HAWK,
	BARCODE_DEVICE_MICROSCAN_GROUP_END,

	BARCODE_DEVICE_DATALOGIC_GROUP     = 200,
	BARCODE_DEVICE_DATALOGIC_M1000,
	BARCODE_DEVICE_DATALOGIC_MATRIX_200,
	BARCODE_DEVICE_DATALOGIC_MATRIX_210,	
	BARCODE_DEVICE_DATALOGIC_GFS4400,
	BARCODE_DEVICE_DATALOGIC_MATRIX_210N,
	BARCODE_DEVICE_DATALOGIC_GROUP_END,

	BARCODE_DEVICE_HONEYWELL_GROUP     = 300,
	BARCODE_DEVICE_HONEYWELL_3310GHD,
	BARCODE_DEVICE_HONEYWELL_1900,
	BARCODE_DEVICE_HONEYWELL_GROUP_END,

	BARCODE_DEVICE_KEYENCE_GROUP       = 400,
	BARCODE_DEVICE_KEYENCE_SR2000,
	BARCODE_DEVICE_KEYENCE_SR751,
	BARCODE_DEVICE_KEYENCE_GROUP_END,

	BARCODE_DEVICE_SICK_GROUP          = 500,
	BARCODE_DEVICE_SICK_442,
	BARCODE_DEVICE_SICK_ICR840,
	BARCODE_DEVICE_SICK_GROUP_END,

	BARCODE_DEVICE_GENERAL_GROUP        = 800,	
	BARCODE_DEVICE_GENERAL_DEVICE_01,	
	BARCODE_DEVICE_GENERAL_DEVICE_02,	
	BARCODE_DEVICE_GENERAL_DEVICE_03,	
	BARCODE_DEVICE_GENERAL_DEVICE_04,
	BARCODE_DEVICE_GENERAL_DEVICE_05,
	BARCODE_DEVICE_GENERAL_DEVICE_06,
	BARCODE_DEVICE_GENERAL_DEVICE_07,
	BARCODE_DEVICE_GENERAL_DEVICE_08,
	BARCODE_DEVICE_GENERAL_GROUP_END,	

	BARCODE_DEVICE_OTHER_GROUP          = 900,
	BARCODE_DEVICE_OTHER_AZUREWAVE,	
	BARCODE_DEVICE_OTHER_GROUP_END,

	BARCODE_DEVICE_RETURN
};
//-------------------------------------------------------------------------------------//
#endif//_Barcode_Define_H_